---
- name: Install homebrew package
  community.general.homebrew:
    name: "{{ item.name | default(item) }}"
    state: present
    install_options: force
  loop: "{{ brew_pkgs }}"
- name: Install homebrew tap
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_taps }}"
- name: Install homebrew application
  homebrew_cask:
    name: "{{ item }}"
    state: latestc
    greedy: true
    install_options: force
    ignore_errors: yes
  with_items: "{{ brew_apps }}"
